### ISSUE TITLE
unknow  token dotdotdot

### ISSUE THREAD

**Issue by nianhua110** [start-react/sb-admin-react#19]
/home/kyle/workspace/sb-admin-react/tools/start.js:76
                middleware: [wpMiddleware, ...hotMiddlewares]
                                           ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at loader (/home/kyle/workspace/sb-admin-react/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js](/home/kyle/workspace/sb-admin-react/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/kyle/workspace/sb-admin-react/tools/run.js:32:18)
    at Module._compile (module.js:410:26)

**Comment by gbamparop** [comment]
I also had this problem with an old version of node. Check if your node version is >= 5.0
