### ISSUE TITLE
error building and starting

### ISSUE THREAD

**Issue by sammosampson** [start-react/sb-admin-react#28]
Any ideas?....

> @ build C:\Users\csampson\Documents\GitHub\MessageDashboard
> babel-node tools/run build

C:\Users\csampson\Documents\GitHub\MessageDashboard\tools\run.js:20
  const task = typeof fn.default === 'undefined' ? fn : fn.default;
  ^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at loader (C:\Users\csampson\Documents\GitHub\MessageDashboard\node_modules\
babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\csampso
n\Documents\GitHub\MessageDashboard\node_modules\babel-register\lib\node.js:154:
7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at C:\Users\csampson\Documents\GitHub\MessageDashboard\node_modules\babel-cl
i\lib\_babel-node.js:159:24
    at Object.<anonymous> (C:\Users\csampson\Documents\GitHub\MessageDashboard\n
ode_modules\babel-cli\lib\_babel-node.js:160:7)

**Comment by sammosampson** [comment]
Apologies, i think this is me not installing node properly
