### ISSUE TITLE
sqlite is not installing

### ISSUE THREAD

**Issue by lalit-sh** [start-react/sb-admin-react#32]
Hi, 
I cloned the project from github and when i tried to npm install it throw me with the error 

         node-pre-gyp ERR! Tried to download: https://mapbox-node-binary.s3.amazonaws.com
         /sqlite3/v3.1.4/node-v51-win32-x64.tar.gz
         node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.4 and node@7.2.1
         (node-v51 ABI) (falling back to source compile with node-gyp)

causing the app to crash every time. I tried solutions about this issue which i found on Google like updating my npm and node version and installing sqlite manually but none helped me out.
I am using npm Version 4.4.0
and node version v7.2.1

These are the errors i am getting
/***********************************************************************************************************/

C:\xampp\htdocs\sb-admin-react>npm install

> sqlite3@3.1.4 install C:\xampp\htdocs\sb-admin-react\node_modules\sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download: https://mapbox-node-binary.s3.amazonaws.com
/sqlite3/v3.1.4/node-v51-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.4 and node@7.2.1
(node-v51 ABI) (falling back to source compile with node-gyp)

C:\xampp\htdocs\sb-admin-react\node_modules\sqlite3>if not defined npm_config_no
de_gyp (node "C:\Users\Lalit Sharma\AppData\Roaming\npm\node_modules\npm\bin\nod
e-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean )  else (node "" c
lean )

C:\xampp\htdocs\sb-admin-react\node_modules\sqlite3>if not defined npm_config_no
de_gyp (node "C:\Users\Lalit Sharma\AppData\Roaming\npm\node_modules\npm\bin\nod
e-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure --fallback-to-
build --module=C:\xampp\htdocs\sb-admin-react\node_modules\sqlite3\lib\binding\n
ode-v51-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\
xampp\htdocs\sb-admin-react\node_modules\sqlite3\lib\binding\node-v51-win32-x64
)  else (node "" configure --fallback-to-build --module=C:\xampp\htdocs\sb-admin
-react\node_modules\sqlite3\lib\binding\node-v51-win32-x64\node_sqlite3.node --m
odule_name=node_sqlite3 --module_path=C:\xampp\htdocs\sb-admin-react\node_module
s\sqlite3\lib\binding\node-v51-win32-x64 )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
HON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\Lalit Sharma\AppData\R
oaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:454:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\Lalit Sharma\AppData\Ro
aming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:480:16)
gyp ERR! stack     at C:\Users\Lalit Sharma\AppData\Roaming\npm\node_modules\npm
\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:111:15)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Lalit Sharma\
\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp
.js" "configure" "--fallback-to-build" "--module=C:\\xampp\\htdocs\\sb-admin-rea
ct\\node_modules\\sqlite3\\lib\\binding\\node-v51-win32-x64\\node_sqlite3.node"
"--module_name=node_sqlite3" "--module_path=C:\\xampp\\htdocs\\sb-admin-react\\n
ode_modules\\sqlite3\\lib\\binding\\node-v51-win32-x64"
gyp ERR! cwd C:\xampp\htdocs\sb-admin-react\node_modules\sqlite3
gyp ERR! node -v v7.2.1
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd configure --fallb
ack-to-build --module=C:\xampp\htdocs\sb-admin-react\node_modules\sqlite3\lib\bi
nding\node-v51-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_p
ath=C:\xampp\htdocs\sb-admin-react\node_modules\sqlite3\lib\binding\node-v51-win
32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\xampp\htdocs\sb-admi
n-react\node_modules\sqlite3\node_modules\node-pre-gyp\lib\util\compile.js:83:29
)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:885:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/chi
ld_process.js:226:5)
node-pre-gyp ERR! System Windows_NT 6.3.9600
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\xampp\\htdo
cs\\sb-admin-react\\node_modules\\sqlite3\\node_modules\\node-pre-gyp\\bin\\node
-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\xampp\htdocs\sb-admin-react\node_modules\sqlite3
node-pre-gyp ERR! node -v v7.2.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.28
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=C:\xampp\
htdocs\sb-admin-react\node_modules\sqlite3\lib\binding\node-v51-win32-x64\node_s
qlite3.node --module_name=node_sqlite3 --module_path=C:\xampp\htdocs\sb-admin-re
act\node_modules\sqlite3\lib\binding\node-v51-win32-x64' (1)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\ch
okidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}
)
npm WARN react-addons-transition-group@15.4.2 requires a peer of react@^15.4.2 b
ut none was installed.
npm WARN Error: EPERM: operation not permitted, scandir 'C:\xampp\htdocs\sb-admi
n-react\node_modules\sqlite3\node_modules'
npm WARN  { Error: EPERM: operation not permitted, scandir 'C:\xampp\htdocs\sb-a
dmin-react\node_modules\sqlite3\node_modules'
npm WARN   errno: -4048,
npm WARN   code: 'EPERM',
npm WARN   syscall: 'scandir',
npm WARN   path: 'C:\\xampp\\htdocs\\sb-admin-react\\node_modules\\sqlite3\\node
_modules' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@3.1.4 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@3.1.4 install script 'node-pre-gyp install --fall
back-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sqlite3
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Lalit Sharma\AppData\Roaming\npm-cache\_logs\2017-03-06T12
_46_25_028Z-debug.log
/*************************************************************************************************************/

**Comment by AcousticGuitar** [comment]
Same Problem here:

184303 error node v7.3.0
184304 error npm  v3.10.10
184305 error code ELIFECYCLE
184306 error sqlite3@3.1.4 install: `node-pre-gyp install --fallback-to-build`
184306 error Exit status 1
184307 error Failed at the sqlite3@3.1.4 install script 'node-pre-gyp install --fallback-to-build'.
184307 error Make sure you have the latest version of node.js and npm installed.
184307 error If you do, this is most likely a problem with the sqlite3 package,
184307 error not with npm itself.
184307 error Tell the author that this fails on your system:
184307 error     node-pre-gyp install --fallback-to-build
184307 error You can get information on how to open an issue for this project with:
184307 error     npm bugs sqlite3
184307 error Or if that isn't available, you can get their info via:
184307 error     npm owner ls sqlite3
184307 error There is likely additional logging output above.
184308 verbose exit [ 1, true ]

**Comment by projenix** [comment]
Same problem here:

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN react-addons-transition-group@15.5.2 requires a peer of react@^15.4.2 but none was installed.
npm ERR! Linux 4.4.0-59-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v7.8.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! sqlite3@3.1.4 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sqlite3@3.1.4 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sqlite3
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/.npm/_logs/2017-05-07T23_09_20_376Z-debug.log

**Comment by gauravprwl14** [comment]
hi,
theme does not support node version 7.x.x.
please install node@6.x.x version and try installing npm module again

**Comment by T-vK** [comment]
Come on that's ridiculous. Just update your sqlite3 package and it works:

```
npm remove sqlite3 --save
npm install sqlite3 --save
npm install
```
